### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by transcendingillusion** [Foxcapades/np-shop-highlight#38]
it is not highlighting anything on my list at all.

**Comment by Foxcapades** [comment]
Thanks for the report. There was a fairly recent update to the Neopets UI that broke it.  I will look into the issue later today.

**Comment by Foxcapades** [comment]
A new version (v1.8.4) has been submitted to the Google Chrome Store for review.  It will be published as soon as that process finishes, however the review process may take up to or more than 24 hours.

If the issue persists or you encounter further issues with the extension please feel free to re-open this issue or create a new one.

Thanks for your patience
