### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by kadem2** [Foxcapades/np-shop-highlight#40]
I've tried a bunch of different items and using the mini stock highlighter, but nothing is ever highlighted. Can I get confirmation that this is working properly? Or is there a bug/issue currently?

**Comment by Foxcapades** [comment]
Hi!  Do you have a paid membership to NP?  If so, the extension currently only works if you enable the NP beta user interface.

If you don't have a paid membership, could you save a copy of a shop page (with items) from your browser for me to test against?

`CTRL+S` (or `CMD+S`) normally works for that, or you can right click the page, hit "View page source" and save that.  For your own privacy i would suggest opening the file in a text editor to search/replace your username and active pet name.

**Comment by kadem2** [comment]
Hello,

I do not have a premium account for NP.

I have attached the shop page. Let me know if I did it right or if you need
to see something else!

Thanks! :)

**Comment by Foxcapades** [comment]
It appears that GitHub stripped out the attachment.  If you wouldn't mind, could you send the attachment to my email (foxcapade@gmail.com) directly?

**Comment by Foxcapades** [comment]
Okay, I know why it's not working for you.  Right now it only supports the beta layout.  I will have to patch it to support both the beta and the original site layouts.  In the meantime, switching to the beta UI via the link at the top-right of the screen should make the plugin work for you.

I switched to the beta layout when it first started and apparently I forgot about that and assumed that the beta layout was just the new default layout :scream:

**Comment by kadem2** [comment]
Yep, that seemed to fix it! I'm not sure if I'm understanding how fresh and
stale items work though. They all appeared green on first refresh, then a
few were yellow, and now none of them have color...

I set up a custom list and that is working perfectly though!

**Comment by kadem2** [comment]
Hi, sorry for the spam. It's working now, I just had to wait for a restock.
Thank you so much for your help! Hopefully this app isn't detectable...

**Comment by Foxcapades** [comment]
The changes to the page that this plugin makes would be detectable if Neopets made use of Javascript's MutationObserver to watch for shop item style changes.  However, at present Neopets is not doing that, and has no way of detecting this plugin.

I went through their javascript again today just to double check.

**Comment by Foxcapades** [comment]
[v1.10.0](https://github.com/Foxcapades/np-shop-highlight/releases/tag/v1.10.0) Has been submitted to the chrome store for review.  It should be published within the next few days.

The new version supports both the old UI as well as the new beta UI.
