### ISSUE TITLE
Item Match custom item lists stopped working

### ISSUE THREAD

**Issue by kadem2** [Foxcapades/np-shop-highlight#41]
Fresh and Stale both work as intended and as shops update, but customizing specific items doesn't work anymore. Not sure if most recent update broke it or TNT changed something on their end. 

Made a list under Styles and gave it a custom colour, then went to item match and used that style and tried a bunch of different item names. None of them get highlighted.

**Comment by Foxcapades** [comment]
Corrected issue with item matching and pushed the fix up to the chrome store.  It should be approved available in the within the next 48 hours.
