### ISSUE TITLE
wildcards where wildcards shouldn't be

### ISSUE THREAD

**Issue by Waterga** [Foxcapades/np-shop-highlight#44]
i've noticed an issue with things being highlighted that shouldn't.  i have my filters set up by price (so a color for 50k - 100k, 100k - 500k, etc.).  i've had quite a few "false positives" without using any wildcards anywhere.  for instance, having the item "hubrid nox" for the card will give a false positive for "hubrid nox commemorative stamp" and "hubrid nox pinata", even though there isn't an asterisk anywhere.

**Comment by Foxcapades** [comment]
I have submitted a fixed version (v1.10.3) of the extension for review.  Going by past experience, it should be available in the chrome store in the next 24 hours.

I'm going to close the issue, but if you still see this happening feel free to reopen it.
